baseurl = "/"
title = "An Autodidact's Dielmma"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Joe Rossi"
#googleAnalytics = "XXX"
#disqusShortname = "XXX"

[Author]
    name = "Joe Rossi"
#    profile = "https://google.com/+XXX"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "An Autodidact's Dilemma"
    description = "The meanderings of my infosec education sprinkled with my other interests"
    github = "https://github.com/generaldespair"
#    gitlab = "https://gitlab.com/XXX"
    linkedin = "https://linkedin.com/in/josepharossi/"
#    gplus = "https://google.com/+XXX"
    twitter = "https://twitter.com/generaldespair"
#    stackoverflow = "https://stackoverflow.com/users/XXX/YYY"
    email = "josepharossi@gmail.com"
    opengraph = true
    shareTwitter = true
#    shareFacebook = true
#    shareGooglePlus = true
    shareLinkedIn = false
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Projects"
    identifier = "project"
    url = "/project/"
    weight = 2
#[[menu.main]]
#    name = "ADD"
#    parent = "project"
#    url = "/project/add"
#[[menu.main]]
#    name = "Contact"
#    url = "/page/contact/"
#    weight = 3

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 4
